CREATE TABLE IF NOT EXISTS TB_CIDADE (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  ESTADO VARCHAR(30) NOT NULL,
  DATAINCLUSAO Datetime(3) NOT NULL,
  DATAALTERACAO Datetime(3),
  DATAEXCLUSAO Datetime(3)
);

CREATE TABLE IF NOT EXISTS TB_CLIENTE (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  SEXO VARCHAR(30) NOT NULL,
  NASCIMENTO DATE NOT NULL,
  IDADE INT NOT NULL,
  ID_CIDADE INT NOT NULL,
  DATAINCLUSAO Datetime(3) NOT NULL,
  DATAALTERACAO Datetime(3),
  DATAEXCLUSAO Datetime(3),
  FOREIGN KEY (ID_CIDADE) REFERENCES TB_CIDADE(ID)
);